export const myProjects = [
  {
    id: 1,
    title: "HTML and CSS Simple Design",
    description: "HTML and CSS Simple design responsive",
    img: "./images/Design1.jpg",
    linkpro: "https://mohamed-elshaowky.github.io/HTML-CSS-Design-one/",
    linkgit: "https://github.com/Mohamed-Elshaowky/HTML-CSS-Design-one",
    category: ["css"],
  },
  {
    id: 2,
    title: "Kasper",
    description: " HTML and CSS Simple and responsive design ",
    img: "./images/Design2.jpg",
    linkpro: "https://mohamed-elshaowky.github.io/Design-two/",
    linkgit: "https://github.com/Mohamed-Elshaowky/Design-two",
    category: ["css"],
  },
  {
    id: 3,
    title: "Gaming Web",
    description: "Gaming Web,HTML and CSS Complics and responsive design ",
    img: "./images/Design3.jpg",
    linkpro: "https://mohamed-elshaowky.github.io/Design-three/",
    linkgit: "https://github.com/Mohamed-Elshaowky/Design-three",
    category: ["css"],
  },
  {
    id: 4,
    title: "Big Design",
    description: "HTML and CSS Complics and responsive big design",
    img: "./images/Design4.jpg",
    linkpro: "https://mohamed-elshaowky.github.io/Design-four/",
    linkgit: "https://github.com/Mohamed-Elshaowky/Design-four",
    category: ["css"],
  },
  {
    id: 5,
    title: "Bondi Design",
    description: "Bondi Design,HTML and CSS simple and responsive big design",
    img: "./images/Bondi.jpg",
    linkpro: "https://mohamed-elshaowky.github.io/Bondi-Desgin/",
    linkgit: "https://github.com/Mohamed-Elshaowky/Bondi-Desgin",
    category: ["css", "js"],
  },
  {
    id: 6,
    title: "Special Design",
    description:
      "Special Design,Javascript ,HTML and CSS simple and responsive big design",
    img: "./images/special.jpg",
    linkpro: "https://mohamed-elshaowky.github.io/Special-Desgin/",
    linkgit: "https://github.com/Mohamed-Elshaowky/Special-Desgin",
    category: ["css", "js"],
  },
  {
    id: 7,
    title: "Food Dish",
    description:
      "Food Dish,React, Javascript, HTML and CSS simple and responsive big design",
    img: "./images/select-dish.jpg",
    linkpro: "https://select-dish.web.app/",
    linkgit: "https://github.com/Mohamed-Elshaowky/Select-dish",
    category: ["react", "js"],
  },
  {
    id: 8,
    title: "Book Store",
    description:
      "Book Store,React, Javascript, HTML and CSS simple and responsive big design",
    img: "./images/Book-store.png",
    linkpro: "https://book-store-e10c5.web.app/",
    linkgit: "https://github.com/Mohamed-Elshaowky/Book-Store",
    category: ["react", "js", "mui"],
  },
  {
    id: 9,
    title: "E-Commerce",
    description:
      "E-Commerce,React, Javascript, HTML and CSS simple and responsive big design",
    img: "./images/E-commerce.jpg",
    linkpro: "https://e-commerce-2004e.web.app",
    linkgit: "https://github.com/Mohamed-Elshaowky/E-Commerce",
    category: ["react", "js", "mui"],
  },
].reverse();
